# Generated by Django 2.1.2 on 2018-10-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dim_area_enquadramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ft_resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_incidencias', models.IntegerField()),
                ('volume_incidencias_porcentagem', models.IntegerField()),
                ('porcentagem_certas', models.IntegerField()),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_ano', to='plataforma_api.Dim_ano')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_area', to='plataforma_api.Dim_area_enquadramento')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_curso', to='plataforma_api.Dim_curso')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_estado', to='plataforma_api.Dim_estado')),
                ('id_regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_regiao', to='plataforma_api.Dim_regiao')),
            ],
        ),
    ]
