# Generated by Django 2.1.2 on 2018-10-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dim_area_enquadramento',
            options={'verbose_name_plural': 'Dim_areas_enquadramento'},
        ),
        migrations.AlterModelOptions(
            name='dim_regiao',
            options={'verbose_name_plural': 'Dim_regioes'},
        ),
    ]
