# Generated by Django 2.1.2 on 2018-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0002_auto_20181024_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dim_ano',
            name='id',
        ),
        migrations.AlterField(
            model_name='dim_ano',
            name='ano',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dim_area_enquadramento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dim_curso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dim_estado',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dim_regiao',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
