# Generated by Django 2.1.2 on 2018-10-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0003_auto_20181025_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_resultado',
            name='id_ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma_api.Dim_ano'),
        ),
    ]
