# Generated by Django 2.1.2 on 2018-10-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0005_auto_20181025_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dim_estado',
            old_name='estado',
            new_name='sigla',
        ),
    ]
