# Generated by Django 2.1.2 on 2018-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0006_auto_20181025_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_resultado',
            name='porcentagem_certas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ft_resultado',
            name='volume_incidencias_porcentagem',
            field=models.FloatField(),
        ),
    ]
