# Generated by Django 2.1.2 on 2018-11-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0008_auto_20181103_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_resultado',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_ano', to='plataforma_api.Dim_ano'),
        ),
    ]
