# Generated by Django 2.1.2 on 2019-05-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0010_ft_associacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ft_associacao',
            name='confianca',
        ),
    ]
