# Generated by Django 2.1.2 on 2019-05-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_api', '0011_remove_ft_associacao_confianca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ft_associacao',
            name='suporte',
        ),
    ]
